Bump minimum Node version to 16.20.0 (#19520)
When using older versions of 16.x we may get this error when attempting
to build the extension:

    TypeError: Cannot assign to read only property 'Symbol(Symbol.iterator)' of object '[object Set]'
      at Object.buildAllowedFlags (node:internal/process/per_thread:375:53)
      at process.get [as allowedNodeEnvironmentFlags] (node:internal/bootstrap/node:279:34)
      at get (<anonymous>)
      at getOwn (node:internal/bootstrap/loaders:182:5)
      at NativeModule.syncExports (node:internal/bootstrap/loaders:294:31)
      at ModuleWrap.<anonymous> (node:internal/bootstrap/loaders:274:22)
      at NativeModule.getESMFacade (node:internal/bootstrap/loaders:279:17)
      at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:259:10)
      at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
      at Function.Module._load (node:internal/modules/cjs/loader:804:15)

This error goes away when upgrading to a later version of 16.x.

To make sure this isn't an issue going forward, this commit bumps the
Node version requirement in `package.json`. 16.20.0 happens to be the
latest version of 16.x (to date).